import { ReactNode } from "react"
import Head from "next/head"
import Footer from "./footer"

type Props = {
    children?: ReactNode
    title?: string
}

const Layout = ({ children, title = "Home" }: Props) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta charSet="utf-8" />
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            {children}
            <Footer/>
        </div>
    )
}

export default Layout;